### ISSUE TITLE
Add BetterAdvancements mod

### ISSUE THREAD

**Issue by joblo2213** [sebinside/CraftBlock#108]
The Advancements window is already getting quite cramped and this will only get worse in the future.  
[BetterAdvancments](https://www.curseforge.com/minecraft/mc-mods/better-advancements) could help:

![grafik](https://user-images.githubusercontent.com/17405009/140912261-9227129c-a524-4b8f-8f4f-44d595011964.png)

**Comment by sebinside** [comment]
discussion was based on vanilla feeling and food on plates
