### ISSUE TITLE
Add drawers for all wood types

### ISSUE THREAD

**Issue by joblo2213** [sebinside/CraftBlock#111]
I think there we are still lacking some fancy drawers. 
Also drawers should be craft able from every wood type, not just the vanilla ones.

Thats why I created [Storage Drawers KAPPA Addon](https://github.com/joblo2213/storage-drawers-kappa).

~~The cursforge page is still waiting for approval (lul 😅), but there already is a release on Github.~~

**Comment by joblo2213** [comment]
v1.0.1 is now available on CursedForge too: https://www.curseforge.com/minecraft/mc-mods/storagedrawerskappa/files

**Comment by sebinside** [comment]
done lul
