### ISSUE TITLE
Astral Sorcery Transmutation not possible

### ISSUE THREAD

**Issue by voruti** [sebinside/CraftBlock#36]
Astral Sorcery's Transmutation works by linking *Floating Crystals* to e.g. Iron Ore Blocks (they get converted to **Starmetal** Ore Blocks).
*Floating Crystals* can either be found in the world (since this is Skyblock this is not possible) or be crafted.

Problem is: *Their* crafting recipe depends on **Starmetal**, which can only be obtained by Transmutation.

**Comment by voruti** [comment]
Recipe for the *Floating Crystal*:

![floatingCrystalRecipe](https://user-images.githubusercontent.com/45130096/124957163-50822a00-e008-11eb-9f89-12850aa72f55.png)
--
Possible solution: Add an alternative/simpler crafting recipe for *Floating Crystals*.

**Comment by voruti** [comment]
Here's how other Skyblock modpacks solve this:

---
Sky Factory 4 / "Core":
![skyFactory4](https://user-images.githubusercontent.com/45130096/125103552-fc407e00-e0cb-11eb-835a-3471b2a34ed6.png)

---
Awakening - Sky of Diamonds (quest book):
![skyOfDiamonds](https://user-images.githubusercontent.com/45130096/125105385-f0ee5200-e0cd-11eb-83a5-d0d4afff22e7.png)

**Comment by joblo2213** [comment]
Maybe a smeltery alloy Recipe? 144mB Molten Iron + 1000mB Liquid Starlight = 144mB Molten Starmetal

Or casting 1000mB Liquid Starlight on an Iron Ingot to create an Starmetal Ingot.

**Comment by voruti** [comment]
How would you get a smeltery?
For "Grout" you will need clay, and I think the only way to get clay is through the transmutation process (that would be another circular dependency). Or am I missing something?

**Comment by joblo2213** [comment]
Totally missed that. I think the smeltery should be a litle bit easier to get. 
Depending it on late game astral sorcery seems not beneficial to me, especially as it is required to get iron tools.

**Comment by voruti** [comment]
A *Floating Crystal* is placed in the map and transmutation can be done that way.
