### ISSUE TITLE
Clay way too hard

### ISSUE THREAD

**Issue by joblo2213** [sebinside/CraftBlock#37]
The smeltery does require some clay for the creation of grout and is essential for creating iron tools or further progression.
Also it could be great for solving #36 if this circular dependency was solved. 

Currently clay is obtained through starlight-transmutation. As starlight transmutation requires a floating crystal which has a very hard crafting recipe (lategame astral sourcery). 

There are two ways to sove this: 
* Make clay easier (maybe using botania)
* Make the folating crystal easily obtainable (would also solve #36, but could cause balancing issues)

**Comment by voruti** [comment]
The smeltery might be essential for creating iron tools, but I don't think iron tools are that important. The manasteel tools from Botania can be used as an alternative.

Apart from #38 and #39 the smeltery isn't involved in any essential recipe for the early- and mid-game.

**Comment by joblo2213** [comment]
To name one that I can remember is the drawer key which is required for the only real early game mass storage.

Although I quite like the idea that you need manasteel tools to advance in the game (eg. get your first diamonds & redstone) I think it's really unintuitive for the player and works against the natural progression. 

Also not that clay is required for feroxia seeds, so the unique crops path also relies on that.
