### ISSUE TITLE
Modpack starting

### ISSUE THREAD

**Issue by deltizy** [sebinside/CraftBlock#69]
i dont think its an issue but the window from the craftblock modpack dont start in the middle. I only want to say it. ( sorry my english isnt perfect)
![dfda1a308260d52ac5975ea378526056](https://user-images.githubusercontent.com/89006412/132983454-7a365ce3-20e0-47f7-8183-eeef03b034a1.jpg)

**Comment by voruti** [comment]
Since you are using MultiMC, you can configure this for your instances by yourself:
![editWindowMmc](https://user-images.githubusercontent.com/45130096/132983787-e7467f6d-dc33-4514-bc3b-1013941bae6d.png)

**Comment by deltizy** [comment]
isnt that the setting where you chnage the size of the window and not where it starts

**Comment by sebinside** [comment]
I don't see what I could do to change this behavior :D
