### ISSUE TITLE
Upload the server artifact to CurseForge

### ISSUE THREAD

**Issue by voruti** [sebinside/CraftBlock#89]
Please also upload the `CraftBlock-Server-vX.Y.Z.zip` to CurseForge [like it's done for this modpack](https://www.curseforge.com/minecraft/modpacks/skyfactory-4) (→ Minecraft 1.12 Server Packs). A button "Zusätzliche Datei hochladen" can be found on every detail page for a "normal" (client) version file ([e.g.](https://www.curseforge.com/minecraft/modpacks/craftblock/files/3470401)).

**Comment by joblo2213** [comment]
Or just document that it can be found on github. 

Training people to leave curseforge is always a good thing 😅
